from app.automation.dependencies import get_automation_service
from app.automation.exceptions import (
    AutomationCacheError,
    AutomationError,
    DuplicateJobError,
    InvalidCronExpressionError,
    InvalidParameterError,
    InvalidScheduleError,
    InvalidTriggerError,
    JobAlreadyRunningError,
    JobDisabledError,
    JobNotFoundError,
    JobPausedError,
    MissingTargetError,
    QueueFullError,
    RetryLimitExceededError,
)
from app.automation.schemas import (
    AutomationJob,
    AutomationPolicy,
    AutomationTrigger,
    AutomationType,
    ExecutionRecord,
    ExecutionStatus,
    HistoryQuery,
    JobPriority,
    JobState,
    QueueItem,
    QueueStatistics,
    TriggerType,
)
from app.automation.service import AutomationService

__all__ = [
    "AutomationJob",
    "AutomationPolicy",
    "AutomationTrigger",
    "AutomationType",
    "ExecutionRecord",
    "ExecutionStatus",
    "HistoryQuery",
    "JobPriority",
    "JobState",
    "QueueItem",
    "QueueStatistics",
    "TriggerType",
    "AutomationService",
    "AutomationError",
    "JobNotFoundError",
    "DuplicateJobError",
    "InvalidTriggerError",
    "InvalidCronExpressionError",
    "JobDisabledError",
    "JobPausedError",
    "MissingTargetError",
    "InvalidParameterError",
    "InvalidScheduleError",
    "RetryLimitExceededError",
    "AutomationCacheError",
    "QueueFullError",
    "JobAlreadyRunningError",
    "get_automation_service",
]
