import type { ProviderId } from '../discovery/types'
import type { ProviderMetadata } from './routing-types'

const METADATA_MAP: Record<ProviderId, Omit<ProviderMetadata, 'lastSuccessfulHealthCheck'>> = {
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au', 'de', 'fr', 'sg'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 1200,
    reliabilityScore: 0.95,
    priority: 1,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_experience', 'filter_by_type', 'easy_apply', 'company_profile', 'salary_range'],
    featureSupport: ['easy_apply', 'company_profile', 'salary_range', 'network'],
  },
  indeed: {
    id: 'indeed',
    name: 'Indeed',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au', 'de', 'fr', 'nl'],
    jobTypes: ['internship', 'fresher', 'experienced'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 800,
    reliabilityScore: 0.93,
    priority: 2,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_salary', 'filter_by_type', 'easy_apply', 'salary_range'],
    featureSupport: ['easy_apply', 'salary_range', 'company_reviews'],
  },
  naukri: {
    id: 'naukri',
    name: 'Naukri',
    version: '1.0.0',
    region: ['india'],
    country: ['in'],
    jobTypes: ['fresher', 'experienced'],
    supportsInternships: false,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 600,
    reliabilityScore: 0.88,
    priority: 3,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_experience', 'filter_by_type'],
    featureSupport: ['salary_range', 'company_profile'],
  },
  foundit: {
    id: 'foundit',
    name: 'Foundit (Monster)',
    version: '1.0.0',
    region: ['india'],
    country: ['in'],
    jobTypes: ['entry', 'experienced'],
    supportsInternships: false,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 700,
    reliabilityScore: 0.82,
    priority: 4,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['salary_range'],
  },
  wellfound: {
    id: 'wellfound',
    name: 'Wellfound (AngelList)',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca'],
    jobTypes: ['experienced'],
    supportsInternships: false,
    supportsFreshers: false,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 900,
    reliabilityScore: 0.85,
    priority: 5,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type', 'easy_apply', 'company_profile', 'salary_range'],
    featureSupport: ['easy_apply', 'company_profile', 'startup_focus', 'equity'],
  },
  ycombinator: {
    id: 'ycombinator',
    name: 'Y Combinator Jobs',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca'],
    jobTypes: ['experienced'],
    supportsInternships: false,
    supportsFreshers: false,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 500,
    reliabilityScore: 0.90,
    priority: 6,
    capabilitySupport: ['search', 'filter_by_type', 'easy_apply', 'company_profile'],
    featureSupport: ['easy_apply', 'company_profile', 'startup_focus', 'yc_alumni'],
  },
  company_careers: {
    id: 'company_careers',
    name: 'Company Careers',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au', 'de', 'fr', 'sg', 'nl'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 1500,
    reliabilityScore: 0.75,
    priority: 7,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type', 'company_profile'],
    featureSupport: ['company_profile', 'direct_apply'],
  },
  internshala: {
    id: 'internshala',
    name: 'Internshala',
    version: '1.0.0',
    region: ['india'],
    country: ['in'],
    jobTypes: ['internship'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 400,
    reliabilityScore: 0.87,
    priority: 8,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['internship_focus', 'training'],
  },
  unstop: {
    id: 'unstop',
    name: 'Unstop (Dare2Compete)',
    version: '1.0.0',
    region: ['india'],
    country: ['in'],
    jobTypes: ['internship', 'fresher'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: false,
    authenticationRequired: false,
    estimatedLatency: 500,
    reliabilityScore: 0.80,
    priority: 9,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['campus_hiring', 'competitions'],
  },
  freshersworld: {
    id: 'freshersworld',
    name: 'Freshersworld',
    version: '1.0.0',
    region: ['india'],
    country: ['in'],
    jobTypes: ['fresher'],
    supportsInternships: false,
    supportsFreshers: true,
    supportsRemote: false,
    authenticationRequired: false,
    estimatedLatency: 500,
    reliabilityScore: 0.78,
    priority: 10,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['fresher_focus', 'campus'],
  },
  greenhouse: {
    id: 'greenhouse',
    name: 'Greenhouse',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au', 'de', 'fr', 'sg', 'nl'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 600,
    reliabilityScore: 0.92,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['ats_integration', 'structured_interviews'],
  },
  lever: {
    id: 'lever',
    name: 'Lever',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 500,
    reliabilityScore: 0.91,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['ats_integration', 'analytics'],
  },
  ashby: {
    id: 'ashby',
    name: 'Ashby',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 400,
    reliabilityScore: 0.90,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type', 'salary_range'],
    featureSupport: ['ats_integration', 'analytics', 'salary_range'],
  },
  smartrecruiters: {
    id: 'smartrecruiters',
    name: 'SmartRecruiters',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au', 'de', 'fr'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 700,
    reliabilityScore: 0.88,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['ats_integration', 'marketplace'],
  },
  workday: {
    id: 'workday',
    name: 'Workday',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au', 'de', 'fr', 'sg', 'nl'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 1000,
    reliabilityScore: 0.89,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['enterprise_ats', 'hcm_integration'],
  },
  jobvite: {
    id: 'jobvite',
    name: 'Jobvite',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 800,
    reliabilityScore: 0.85,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['enterprise_ats', 'social_recruiting'],
  },
  bamboohr: {
    id: 'bamboohr',
    name: 'BambooHR',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au'],
    jobTypes: ['fresher', 'experienced'],
    supportsInternships: false,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 600,
    reliabilityScore: 0.86,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['smb_hr', 'hr_integration'],
  },
  icims: {
    id: 'icims',
    name: 'iCIMS',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 900,
    reliabilityScore: 0.87,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['enterprise_ats', 'talent_community'],
  },
  oracle: {
    id: 'oracle',
    name: 'Oracle Recruiting',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au', 'de', 'fr', 'sg', 'nl'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 1200,
    reliabilityScore: 0.88,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['enterprise_ats', 'cloud_hcm'],
  },
  successfactors: {
    id: 'successfactors',
    name: 'SAP SuccessFactors',
    version: '1.0.0',
    region: ['global'],
    country: ['us', 'in', 'uk', 'ca', 'au', 'de', 'fr', 'sg', 'nl'],
    jobTypes: ['internship', 'fresher', 'experienced', 'executive'],
    supportsInternships: true,
    supportsFreshers: true,
    supportsRemote: true,
    authenticationRequired: false,
    estimatedLatency: 1500,
    reliabilityScore: 0.86,
    priority: 100,
    capabilitySupport: ['search', 'filter_by_location', 'filter_by_type'],
    featureSupport: ['enterprise_ats', 'performance_management'],
  },
}

const healthCheckTimestamps: Partial<Record<ProviderId, string>> = {}

export const providerMetadataService = {
  get(id: ProviderId): ProviderMetadata {
    const base = METADATA_MAP[id]
    if (!base) {
      return {
        id,
        name: id,
        version: '1.0.0',
        region: ['global'],
        country: [],
        jobTypes: ['experienced'],
        supportsInternships: false,
        supportsFreshers: false,
        supportsRemote: false,
        authenticationRequired: false,
        estimatedLatency: 1000,
        reliabilityScore: 0.5,
        priority: 100,
        capabilitySupport: [],
        featureSupport: [],
        lastSuccessfulHealthCheck: null,
      }
    }
    return {
      ...base,
      lastSuccessfulHealthCheck: healthCheckTimestamps[id] ?? null,
    }
  },

  getAll(): ProviderMetadata[] {
    const ids = Object.keys(METADATA_MAP) as ProviderId[]
    return ids.map(id => this.get(id))
  },

  getByRegion(region: string): ProviderMetadata[] {
    return this.getAll().filter(m => m.region.includes(region))
  },

  getByCountry(country: string): ProviderMetadata[] {
    return this.getAll().filter(m => m.country.includes(country))
  },

  getByJobType(jobType: string): ProviderMetadata[] {
    return this.getAll().filter(m => m.jobTypes.includes(jobType))
  },

  updateHealthCheck(id: ProviderId, success: boolean): void {
    if (success) {
      healthCheckTimestamps[id] = new Date().toISOString()
    }
  },
}
